### ISSUE TITLE
2 задание, задача 2 не верная

### ISSUE THREAD

**Issue by tim-teacher** [MoonBastart/My-works#1]
Homework2/src/by/it_academy/task2/TheSame.java
Если подать такой массив:
float[] justArray2 = new float[] {7, 26, 4, 4,4, 17, 13, 8, 7, 4};
то работает не верно, выдает:
[7.0] - is repeated 2 times
[4.0] - is repeated 4 times
[4.0] - is repeated 3 times
[4.0] - is repeated 2 times

**Comment by MoonBastart** [comment]
fixed
